### ISSUE TITLE
ReadBits drops bits on encountering the last byte of http response body

### ISSUE THREAD

**Issue by itchyny** [dgryski/go-bitstream#6]
We encountered some weird problem that we can decode from local file but fail to decode http response. The problem is that the `Read` function of resp.Body yields the last byte with io.EOF.

```go
package main

import (
	"fmt"
	"net/http"
	"os"

	bitstream "github.com/dgryski/go-bitstream"
)

func main() {
	resp, err := http.Get("http://example.com")
	if err != nil {
		fmt.Fprintf(os.Stderr, "%v\n", err)
		os.Exit(1)
	}
	defer resp.Body.Close()
	br := bitstream.NewReader(resp.Body)
	for {
		// b, err := br.ReadByte()
		b, err := br.ReadBits(8)
		fmt.Printf("%q %v\n", b, err)
		if err != nil {
			break
		}
	}
}
```
yields the output
```
...
'<' <nil>
'/' <nil>
'h' <nil>
't' <nil>
'm' <nil>
'l' <nil>
'>' <nil>
'\x00' EOF
```
dropping the last `\n` byte.

Using the `b, err := br.ReadByte()` line yields
```
'<' <nil>
'/' <nil>
'h' <nil>
't' <nil>
'm' <nil>
'l' <nil>
'>' <nil>
'\n' EOF
```
which works fine.

The above example shows the cases for reading each 8 bits, but it occurs with arbitrary argument for ReadBits used on resp.Body and we fail to decode the last bits.  I think the library should not return error quickly at https://github.com/dgryski/go-bitstream/blob/7d46cd22d/bitstream.go#L138.

There's a dirty workaround to avoid the problem by wrapping resp.Body with the following struct.
```go
type ReaderWrapper struct {
	r io.Reader
}

func NewReaderWrapper(r io.Reader) *ReaderWrapper {
	return &ReaderWrapper{r}
}

func (r *ReaderWrapper) Read(p []byte) (n int, err error) {
	n, err = r.r.Read(p)
	if n == len(p) {
		err = nil
	}
	return
}
```
But this is too hacky isn't it.

What do you think?

**Comment by dgryski** [comment]
Sorry, I missed this bug.  I'll look into fixing it.

**Comment by itchyny** [comment]
Thank you!

**Comment by dgryski** [comment]
Just realized I need a better fix for this. I'll push another commit tomorrow.
