### ISSUE TITLE
RFC: BitReader.Reset() and BitReader.SetReader(io.Reader) to allow use with sync.Pool

### ISSUE THREAD

**Issue by marcel** [dgryski/go-bitstream#7]
I'd like to be able to reuse a `BitReader` from a `sync.Pool` but have no way to zero-value out its 3 encapsulated fields.

In order to use it in a `sync.Pool` I'd need to implement both a `Reset()` method (to set `count` to `0`) as well as a `SetReader(io.Reader)` method to swap out `r` without allocating a new `BitReader`.

(To be symmetrical between the reader the writer `Reset()` and `SetWriter()` could also be added to `BitWriter` but I don't personally have a need for it.)

I'll happily implement both methods and tests but just wanted to introduce the idea first to see if you're open to the addition.

An alternative would be a single method `Reset(io.Reader)` which accomplishes both. While this is a more succinct interface the common pattern for me (with a thin wrapper around `sync.Pool`) is to prepare an object (i.e. `SetReader()`) when getting it from the `sync.Pool` and have the `sync.Pool` take care of resetting it (i.e. `Reset()`) implicitly after i've `Put()` it back into the pool.

**Comment by dgryski** [comment]
Sure, I'll accept a patch for `Reset(io.Reader`.   Having one for the Writer probably makes sense too, even if it's not yet going to be used.

**Comment by dgryski** [comment]
Implemented in https://github.com/dgryski/go-bitstream/pull/8
